#-------------------------------------------------
#
# Project created by QtCreator 2019-03-26T12:24:37
#
#-------------------------------------------------

QT       += core gui \

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = tutorial
TEMPLATE = app

# Path to cuda toolkit install
CUDA_DIR      = /usr/local/cuda
# Path to header and libs files
INCLUDEPATH  += $$CUDA_DIR/include
QMAKE_LIBDIR += $$CUDA_DIR/lib64     # Note I'm using a 64 bits Operating system
# libs used in your code
LIBS += -lcudart -lcuda
# GPU architecture
CUDA_ARCH     = sm_20                # Yeah! I've a new device. Adjust with your compute capability
# Here are some NVCC flags I've always used by default.
NVCCFLAGS     = --compiler-options -fno-strict-aliasing -use_fast_math --ptxas-options=-v

SOURCES += main.cpp \
    World/world.cpp \
    World/Gridworld/gridworld.cpp \
    World/Gridworld/gridworld_agent.cpp \
    World/Gridworld/gridworld_ball.cpp \
    World/Gridworld/gridworld_event.cpp \
    World/Gridworld/gridworld_getset.cpp \
    View/view.cpp \
    View/Gridworld/gridworldview.cpp \
    View/Gridworld/gridworldview_agent.cpp \
    View/Gridworld/gridworldview_ball.cpp \
    View/Gridworld/gridworldview_score.cpp \
    Player/player.cpp \
    Player/randomplayer.cpp \
    Player/tabularq.cpp \
    Interaction_Handler/Gridworld/gridworld_ih.cpp \
    Interaction_Handler/Gridworld/tabularqih.cpp \
    Interaction_Handler/Gridworld/mlpqih.cpp \
    Interaction_Handler/Gridworld/gridworld_ih_getset.cpp \
    Interaction_Handler/Gridworld/gridworld_ih_input.cpp \
    Interaction_Handler/Gridworld/gridworld_ih_reward.cpp \
    Interaction_Handler/Gridworld/randomih.cpp \
    Util/neural_network.cpp \
    World/Gridworld/gridworld_score.cpp \
    Player/mlpq.cpp \
    Util/util_functions.cpp \
    Player/qlearningplayer.cpp \
    Interaction_Handler/Gridworld/visiongrid_ih.cpp \
    World/Gridworld/gridworld_add_player.cpp \
    World/Gridworld/gridworld_event_log.cpp \
    World/Gridworld/gridworld_check_pixel.cpp \
    World/Gridworld/gridworld_reset.cpp \
    World/Gridworld/gridworld_simulation.cpp \
    Player/qv.cpp \
    Player/dqn.cpp \
    Util/cytonRL/ale/common/ColourPalette.cpp \
    Util/cytonRL/ale/common/Constants.cpp \
    Util/cytonRL/ale/common/display_screen.cpp \
    Util/cytonRL/ale/common/Log.cpp \
    Util/cytonRL/ale/common/ScreenExporter.cpp \
    Util/cytonRL/ale/common/SoundExporter.cpp \
    Util/cytonRL/ale/common/SoundNull.cxx \
    Util/cytonRL/ale/common/SoundSDL.cxx \
    Util/cytonRL/ale/controllers/ale_controller.cpp \
    Util/cytonRL/ale/controllers/fifo_controller.cpp \
    Util/cytonRL/ale/controllers/rlglue_controller.cpp \
    Util/cytonRL/ale/emucore/m6502/src/Device.cxx \
    Util/cytonRL/ale/emucore/m6502/src/M6502.cxx \
    Util/cytonRL/ale/emucore/m6502/src/M6502Hi.cxx \
    Util/cytonRL/ale/emucore/m6502/src/M6502Low.cxx \
    Util/cytonRL/ale/emucore/m6502/src/NullDev.cxx \
    Util/cytonRL/ale/emucore/m6502/src/System.cxx \
    Util/cytonRL/ale/emucore/AtariVox.cxx \
    Util/cytonRL/ale/emucore/Booster.cxx \
    Util/cytonRL/ale/emucore/Cart.cxx \
    Util/cytonRL/ale/emucore/Cart0840.cxx \
    Util/cytonRL/ale/emucore/Cart2K.cxx \
    Util/cytonRL/ale/emucore/Cart3E.cxx \
    Util/cytonRL/ale/emucore/Cart3F.cxx \
    Util/cytonRL/ale/emucore/Cart4A50.cxx \
    Util/cytonRL/ale/emucore/Cart4K.cxx \
    Util/cytonRL/ale/emucore/CartAR.cxx \
    Util/cytonRL/ale/emucore/CartCV.cxx \
    Util/cytonRL/ale/emucore/CartDPC.cxx \
    Util/cytonRL/ale/emucore/CartE0.cxx \
    Util/cytonRL/ale/emucore/CartE7.cxx \
    Util/cytonRL/ale/emucore/CartF4.cxx \
    Util/cytonRL/ale/emucore/CartF4SC.cxx \
    Util/cytonRL/ale/emucore/CartF6.cxx \
    Util/cytonRL/ale/emucore/CartF6SC.cxx \
    Util/cytonRL/ale/emucore/CartF8.cxx \
    Util/cytonRL/ale/emucore/CartF8SC.cxx \
    Util/cytonRL/ale/emucore/CartFASC.cxx \
    Util/cytonRL/ale/emucore/CartFE.cxx \
    Util/cytonRL/ale/emucore/CartMB.cxx \
    Util/cytonRL/ale/emucore/CartMC.cxx \
    Util/cytonRL/ale/emucore/CartUA.cxx \
    Util/cytonRL/ale/emucore/Console.cxx \
    Util/cytonRL/ale/emucore/Control.cxx \
    Util/cytonRL/ale/emucore/Deserializer.cxx \
    Util/cytonRL/ale/emucore/Driving.cxx \
    Util/cytonRL/ale/emucore/Event.cxx \
    Util/cytonRL/ale/emucore/FSNode.cxx \
    Util/cytonRL/ale/emucore/Joystick.cxx \
    Util/cytonRL/ale/emucore/Keyboard.cxx \
    Util/cytonRL/ale/emucore/M6532.cxx \
    Util/cytonRL/ale/emucore/MD5.cxx \
    Util/cytonRL/ale/emucore/MediaSrc.cxx \
    Util/cytonRL/ale/emucore/OSystem.cxx \
    Util/cytonRL/ale/emucore/Paddles.cxx \
    Util/cytonRL/ale/emucore/Props.cxx \
    Util/cytonRL/ale/emucore/PropsSet.cxx \
    Util/cytonRL/ale/emucore/Random.cxx \
    Util/cytonRL/ale/emucore/Serializer.cxx \
    Util/cytonRL/ale/emucore/Settings.cxx \
    Util/cytonRL/ale/emucore/SpeakJet.cxx \
    Util/cytonRL/ale/emucore/Switches.cxx \
    Util/cytonRL/ale/emucore/TIA.cxx \
    Util/cytonRL/ale/emucore/TIASnd.cxx \
    Util/cytonRL/ale/environment/ale_state.cpp \
    Util/cytonRL/ale/environment/phosphor_blend.cpp \
    Util/cytonRL/ale/environment/stella_environment.cpp \
    Util/cytonRL/ale/environment/stella_environment_wrapper.cpp \
    Util/cytonRL/ale/games/supported/Adventure.cpp \
    Util/cytonRL/ale/games/supported/AirRaid.cpp \
    Util/cytonRL/ale/games/supported/Alien.cpp \
    Util/cytonRL/ale/games/supported/Amidar.cpp \
    Util/cytonRL/ale/games/supported/Assault.cpp \
    Util/cytonRL/ale/games/supported/Asterix.cpp \
    Util/cytonRL/ale/games/supported/Asteroids.cpp \
    Util/cytonRL/ale/games/supported/Atlantis.cpp \
    Util/cytonRL/ale/games/supported/BankHeist.cpp \
    Util/cytonRL/ale/games/supported/BattleZone.cpp \
    Util/cytonRL/ale/games/supported/BeamRider.cpp \
    Util/cytonRL/ale/games/supported/Berzerk.cpp \
    Util/cytonRL/ale/games/supported/Bowling.cpp \
    Util/cytonRL/ale/games/supported/Boxing.cpp \
    Util/cytonRL/ale/games/supported/Breakout.cpp \
    Util/cytonRL/ale/games/supported/Carnival.cpp \
    Util/cytonRL/ale/games/supported/Centipede.cpp \
    Util/cytonRL/ale/games/supported/ChopperCommand.cpp \
    Util/cytonRL/ale/games/supported/CrazyClimber.cpp \
    Util/cytonRL/ale/games/supported/Defender.cpp \
    Util/cytonRL/ale/games/supported/DemonAttack.cpp \
    Util/cytonRL/ale/games/supported/DonkeyKong.cpp \
    Util/cytonRL/ale/games/supported/DoubleDunk.cpp \
    Util/cytonRL/ale/games/supported/ElevatorAction.cpp \
    Util/cytonRL/ale/games/supported/Enduro.cpp \
    Util/cytonRL/ale/games/supported/FishingDerby.cpp \
    Util/cytonRL/ale/games/supported/Freeway.cpp \
    Util/cytonRL/ale/games/supported/Frogger.cpp \
    Util/cytonRL/ale/games/supported/Frostbite.cpp \
    Util/cytonRL/ale/games/supported/Galaxian.cpp \
    Util/cytonRL/ale/games/supported/Gopher.cpp \
    Util/cytonRL/ale/games/supported/Gravitar.cpp \
    Util/cytonRL/ale/games/supported/Hero.cpp \
    Util/cytonRL/ale/games/supported/IceHockey.cpp \
    Util/cytonRL/ale/games/supported/JamesBond.cpp \
    Util/cytonRL/ale/games/supported/JourneyEscape.cpp \
    Util/cytonRL/ale/games/supported/Kaboom.cpp \
    Util/cytonRL/ale/games/supported/Kangaroo.cpp \
    Util/cytonRL/ale/games/supported/KeystoneKapers.cpp \
    Util/cytonRL/ale/games/supported/Kingkong.cpp \
    Util/cytonRL/ale/games/supported/Koolaid.cpp \
    Util/cytonRL/ale/games/supported/Krull.cpp \
    Util/cytonRL/ale/games/supported/KungFuMaster.cpp \
    Util/cytonRL/ale/games/supported/LaserGates.cpp \
    Util/cytonRL/ale/games/supported/LostLuggage.cpp \
    Util/cytonRL/ale/games/supported/MontezumaRevenge.cpp \
    Util/cytonRL/ale/games/supported/MrDo.cpp \
    Util/cytonRL/ale/games/supported/MsPacman.cpp \
    Util/cytonRL/ale/games/supported/NameThisGame.cpp \
    Util/cytonRL/ale/games/supported/Phoenix.cpp \
    Util/cytonRL/ale/games/supported/Pitfall.cpp \
    Util/cytonRL/ale/games/supported/Pong.cpp \
    Util/cytonRL/ale/games/supported/Pooyan.cpp \
    Util/cytonRL/ale/games/supported/PrivateEye.cpp \
    Util/cytonRL/ale/games/supported/QBert.cpp \
    Util/cytonRL/ale/games/supported/RiverRaid.cpp \
    Util/cytonRL/ale/games/supported/RoadRunner.cpp \
    Util/cytonRL/ale/games/supported/RoboTank.cpp \
    Util/cytonRL/ale/games/supported/Seaquest.cpp \
    Util/cytonRL/ale/games/supported/SirLancelot.cpp \
    Util/cytonRL/ale/games/supported/Skiing.cpp \
    Util/cytonRL/ale/games/supported/Solaris.cpp \
    Util/cytonRL/ale/games/supported/SpaceInvaders.cpp \
    Util/cytonRL/ale/games/supported/StarGunner.cpp \
    Util/cytonRL/ale/games/supported/Tennis.cpp \
    Util/cytonRL/ale/games/supported/Tetris.cpp \
    Util/cytonRL/ale/games/supported/TimePilot.cpp \
    Util/cytonRL/ale/games/supported/Trondead.cpp \
    Util/cytonRL/ale/games/supported/Turmoil.cpp \
    Util/cytonRL/ale/games/supported/Tutankham.cpp \
    Util/cytonRL/ale/games/supported/UpNDown.cpp \
    Util/cytonRL/ale/games/supported/Venture.cpp \
    Util/cytonRL/ale/games/supported/VideoPinball.cpp \
    Util/cytonRL/ale/games/supported/WizardOfWor.cpp \
    Util/cytonRL/ale/games/supported/YarsRevenge.cpp \
    Util/cytonRL/ale/games/supported/Zaxxon.cpp \
    Util/cytonRL/ale/games/Roms.cpp \
    Util/cytonRL/ale/games/RomSettings.cpp \
    Util/cytonRL/ale/games/RomUtils.cpp \
    Util/cytonRL/ale/os_dependent/FSNodePOSIX.cxx \
    Util/cytonRL/ale/os_dependent/FSNodeWin32.cxx \
    Util/cytonRL/ale/os_dependent/OSystemUNIX.cxx \
    Util/cytonRL/ale/os_dependent/OSystemWin32.cxx \
    Util/cytonRL/ale/os_dependent/SettingsUNIX.cxx \
    Util/cytonRL/ale/os_dependent/SettingsWin32.cxx \
    Util/cytonRL/ale/ale_interface.cpp \
    Util/cytonRL/ale/main.cpp \
    Util/cnn.cpp \
    Util/cytonRL/ale/emucore/rsynth/darray.c \
    Util/cytonRL/ale/emucore/rsynth/elements.c \
    Util/cytonRL/ale/emucore/rsynth/holmes.c \
    Util/cytonRL/ale/emucore/rsynth/opsynth.c \
    Util/cytonRL/ale/emucore/rsynth/phones.c \
    Util/cytonRL/ale/emucore/rsynth/phtoelm.c \
    Util/cytonRL/ale/emucore/rsynth/trie.c \
    Util/cytonRL/ale/external/TinyMT/tinymt32.c

HEADERS  += \
    World/world.h \
    World/Gridworld/gridworld.h \
    World/Gridworld/gridworld_agent.h \
    World/Gridworld/gridworld_ball.h \
    World/Gridworld/gridworld_event.h \
    World/Gridworld/gridworld_score.h \
    View/view.h \
    View/Gridworld/gridworldview_agent.h \
    View/Gridworld/gridworldview_ball.h \
    View/Gridworld/gridworldview.h \
    View/Gridworld/gridworldview_score.h \
    Player/player.h \
    Player/randomplayer.h \
    Player/tabularq.h \
    Util/neural_network.h \
    Interaction_Handler/Gridworld/gridworld_ih.h \
    Interaction_Handler/Gridworld/tabularqih.h \
    Interaction_Handler/Gridworld/mlpqih.h \
    Interaction_Handler/Gridworld/randomih.h \
    Player/mlpq.h \
    Util/util_functions.h \
    Player/qlearningplayer.h \
    Interaction_Handler/Gridworld/visiongrid_ih.h \
    Player/qv.h \
    Interaction_Handler/Gridworld/gridworld_ih.h.hD2917 \
    Interaction_Handler/Gridworld/gridworld_ih.h.PW9990 \
    Player/dqn.h \
    Util/cytonLib/ActivationLayer.h \
    Util/cytonLib/basicHeads.h \
    Util/cytonLib/ConvolutionLayer.h \
    Util/cytonLib/cublasWrapper.h \
    Util/cytonLib/DeviceMatrix.h \
    Util/cytonLib/DevMatReal.h \
    Util/cytonLib/DueLinLayer.h \
    Util/cytonLib/Global.h \
    Util/cytonLib/HostMatReal.h \
    Util/cytonLib/HostMatrix.h \
    Util/cytonLib/Layer.h \
    Util/cytonLib/LinearLayer.h \
    Util/cytonLib/Matrix.h \
    Util/cytonLib/MatrixGradient.h \
    Util/cytonLib/Network.h \
    Util/cytonLib/NumberProbe.h \
    Util/cytonLib/NumberProbes.h \
    Util/cytonLib/ParametersBase.h \
    Util/cytonLib/SoftmaxLayer.h \
    Util/cytonLib/utils.h \
    Util/cytonLib/Variable.h \
    Util/cytonLib/Weight.h \
    Util/cytonLib/WeightFactory.h \
    Util/cytonLib/xlCLib.h \
    Util/cytonRL/ale/common/Array.hxx \
    Util/cytonRL/ale/common/ColourPalette.hpp \
    Util/cytonRL/ale/common/Constants.h \
    Util/cytonRL/ale/common/display_screen.h \
    Util/cytonRL/ale/common/Log.hpp \
    Util/cytonRL/ale/common/misc_tools.h \
    Util/cytonRL/ale/common/Palettes.hpp \
    Util/cytonRL/ale/common/ScreenExporter.hpp \
    Util/cytonRL/ale/common/SoundExporter.hpp \
    Util/cytonRL/ale/common/SoundNull.hxx \
    Util/cytonRL/ale/common/SoundSDL.hxx \
    Util/cytonRL/ale/common/Version.hxx \
    Util/cytonRL/ale/common/VideoModeList.hxx \
    Util/cytonRL/ale/controllers/ale_controller.hpp \
    Util/cytonRL/ale/controllers/fifo_controller.hpp \
    Util/cytonRL/ale/controllers/rlglue_controller.hpp \
    Util/cytonRL/ale/emucore/m6502/src/bspf/src/bspf.hxx \
    Util/cytonRL/ale/emucore/m6502/src/Device.hxx \
    Util/cytonRL/ale/emucore/m6502/src/M6502.hxx \
    Util/cytonRL/ale/emucore/m6502/src/M6502Hi.hxx \
    Util/cytonRL/ale/emucore/m6502/src/M6502Low.hxx \
    Util/cytonRL/ale/emucore/m6502/src/NullDev.hxx \
    Util/cytonRL/ale/emucore/m6502/src/System.hxx \
    Util/cytonRL/ale/emucore/rsynth/config.h \
    Util/cytonRL/ale/emucore/rsynth/darray.h \
    Util/cytonRL/ale/emucore/rsynth/phfeat.h \
    Util/cytonRL/ale/emucore/rsynth/phones.h \
    Util/cytonRL/ale/emucore/rsynth/phtoelm.h \
    Util/cytonRL/ale/emucore/rsynth/rsynth.h \
    Util/cytonRL/ale/emucore/rsynth/trie.h \
    Util/cytonRL/ale/emucore/rsynth/useconfig.h \
    Util/cytonRL/ale/emucore/AtariVox.hxx \
    Util/cytonRL/ale/emucore/Booster.hxx \
    Util/cytonRL/ale/emucore/Cart.hxx \
    Util/cytonRL/ale/emucore/Cart0840.hxx \
    Util/cytonRL/ale/emucore/Cart2K.hxx \
    Util/cytonRL/ale/emucore/Cart3E.hxx \
    Util/cytonRL/ale/emucore/Cart3F.hxx \
    Util/cytonRL/ale/emucore/Cart4A50.hxx \
    Util/cytonRL/ale/emucore/Cart4K.hxx \
    Util/cytonRL/ale/emucore/CartAR.hxx \
    Util/cytonRL/ale/emucore/CartCV.hxx \
    Util/cytonRL/ale/emucore/CartDPC.hxx \
    Util/cytonRL/ale/emucore/CartE0.hxx \
    Util/cytonRL/ale/emucore/CartE7.hxx \
    Util/cytonRL/ale/emucore/CartF4.hxx \
    Util/cytonRL/ale/emucore/CartF4SC.hxx \
    Util/cytonRL/ale/emucore/CartF6.hxx \
    Util/cytonRL/ale/emucore/CartF6SC.hxx \
    Util/cytonRL/ale/emucore/CartF8.hxx \
    Util/cytonRL/ale/emucore/CartF8SC.hxx \
    Util/cytonRL/ale/emucore/CartFASC.hxx \
    Util/cytonRL/ale/emucore/CartFE.hxx \
    Util/cytonRL/ale/emucore/CartMB.hxx \
    Util/cytonRL/ale/emucore/CartMC.hxx \
    Util/cytonRL/ale/emucore/CartUA.hxx \
    Util/cytonRL/ale/emucore/Console.hxx \
    Util/cytonRL/ale/emucore/Control.hxx \
    Util/cytonRL/ale/emucore/DefProps.hxx \
    Util/cytonRL/ale/emucore/Deserializer.hxx \
    Util/cytonRL/ale/emucore/Driving.hxx \
    Util/cytonRL/ale/emucore/Event.hxx \
    Util/cytonRL/ale/emucore/FSNode.hxx \
    Util/cytonRL/ale/emucore/Joystick.hxx \
    Util/cytonRL/ale/emucore/Keyboard.hxx \
    Util/cytonRL/ale/emucore/M6532.hxx \
    Util/cytonRL/ale/emucore/MD5.hxx \
    Util/cytonRL/ale/emucore/MediaSrc.hxx \
    Util/cytonRL/ale/emucore/OSystem.hxx \
    Util/cytonRL/ale/emucore/Paddles.hxx \
    Util/cytonRL/ale/emucore/Props.hxx \
    Util/cytonRL/ale/emucore/PropsSet.hxx \
    Util/cytonRL/ale/emucore/Random.hxx \
    Util/cytonRL/ale/emucore/Serializer.hxx \
    Util/cytonRL/ale/emucore/Settings.hxx \
    Util/cytonRL/ale/emucore/Sound.hxx \
    Util/cytonRL/ale/emucore/SpeakJet.hxx \
    Util/cytonRL/ale/emucore/Switches.hxx \
    Util/cytonRL/ale/emucore/TIA.hxx \
    Util/cytonRL/ale/emucore/TIASnd.hxx \
    Util/cytonRL/ale/environment/ale_ram.hpp \
    Util/cytonRL/ale/environment/ale_screen.hpp \
    Util/cytonRL/ale/environment/ale_state.hpp \
    Util/cytonRL/ale/environment/phosphor_blend.hpp \
    Util/cytonRL/ale/environment/stella_environment.hpp \
    Util/cytonRL/ale/environment/stella_environment_wrapper.hpp \
    Util/cytonRL/ale/external/TinyMT/tinymt32.h \
    Util/cytonRL/ale/games/supported/Adventure.hpp \
    Util/cytonRL/ale/games/supported/AirRaid.hpp \
    Util/cytonRL/ale/games/supported/Alien.hpp \
    Util/cytonRL/ale/games/supported/Amidar.hpp \
    Util/cytonRL/ale/games/supported/Assault.hpp \
    Util/cytonRL/ale/games/supported/Asterix.hpp \
    Util/cytonRL/ale/games/supported/Asteroids.hpp \
    Util/cytonRL/ale/games/supported/Atlantis.hpp \
    Util/cytonRL/ale/games/supported/BankHeist.hpp \
    Util/cytonRL/ale/games/supported/BattleZone.hpp \
    Util/cytonRL/ale/games/supported/BeamRider.hpp \
    Util/cytonRL/ale/games/supported/Berzerk.hpp \
    Util/cytonRL/ale/games/supported/Bowling.hpp \
    Util/cytonRL/ale/games/supported/Boxing.hpp \
    Util/cytonRL/ale/games/supported/Breakout.hpp \
    Util/cytonRL/ale/games/supported/Carnival.hpp \
    Util/cytonRL/ale/games/supported/Centipede.hpp \
    Util/cytonRL/ale/games/supported/ChopperCommand.hpp \
    Util/cytonRL/ale/games/supported/CrazyClimber.hpp \
    Util/cytonRL/ale/games/supported/Defender.hpp \
    Util/cytonRL/ale/games/supported/DemonAttack.hpp \
    Util/cytonRL/ale/games/supported/DonkeyKong.hpp \
    Util/cytonRL/ale/games/supported/DoubleDunk.hpp \
    Util/cytonRL/ale/games/supported/ElevatorAction.hpp \
    Util/cytonRL/ale/games/supported/Enduro.hpp \
    Util/cytonRL/ale/games/supported/FishingDerby.hpp \
    Util/cytonRL/ale/games/supported/Freeway.hpp \
    Util/cytonRL/ale/games/supported/Frogger.hpp \
    Util/cytonRL/ale/games/supported/Frostbite.hpp \
    Util/cytonRL/ale/games/supported/Galaxian.hpp \
    Util/cytonRL/ale/games/supported/Gopher.hpp \
    Util/cytonRL/ale/games/supported/Gravitar.hpp \
    Util/cytonRL/ale/games/supported/Hero.hpp \
    Util/cytonRL/ale/games/supported/IceHockey.hpp \
    Util/cytonRL/ale/games/supported/JamesBond.hpp \
    Util/cytonRL/ale/games/supported/JourneyEscape.hpp \
    Util/cytonRL/ale/games/supported/Kaboom.hpp \
    Util/cytonRL/ale/games/supported/Kangaroo.hpp \
    Util/cytonRL/ale/games/supported/KeystoneKapers.hpp \
    Util/cytonRL/ale/games/supported/Kingkong.hpp \
    Util/cytonRL/ale/games/supported/Koolaid.hpp \
    Util/cytonRL/ale/games/supported/Krull.hpp \
    Util/cytonRL/ale/games/supported/KungFuMaster.hpp \
    Util/cytonRL/ale/games/supported/LaserGates.hpp \
    Util/cytonRL/ale/games/supported/LostLuggage.hpp \
    Util/cytonRL/ale/games/supported/MontezumaRevenge.hpp \
    Util/cytonRL/ale/games/supported/MrDo.hpp \
    Util/cytonRL/ale/games/supported/MsPacman.hpp \
    Util/cytonRL/ale/games/supported/NameThisGame.hpp \
    Util/cytonRL/ale/games/supported/Phoenix.hpp \
    Util/cytonRL/ale/games/supported/Pitfall.hpp \
    Util/cytonRL/ale/games/supported/Pong.hpp \
    Util/cytonRL/ale/games/supported/Pooyan.hpp \
    Util/cytonRL/ale/games/supported/PrivateEye.hpp \
    Util/cytonRL/ale/games/supported/QBert.hpp \
    Util/cytonRL/ale/games/supported/RiverRaid.hpp \
    Util/cytonRL/ale/games/supported/RoadRunner.hpp \
    Util/cytonRL/ale/games/supported/RoboTank.hpp \
    Util/cytonRL/ale/games/supported/Seaquest.hpp \
    Util/cytonRL/ale/games/supported/SirLancelot.hpp \
    Util/cytonRL/ale/games/supported/Skiing.hpp \
    Util/cytonRL/ale/games/supported/Solaris.hpp \
    Util/cytonRL/ale/games/supported/SpaceInvaders.hpp \
    Util/cytonRL/ale/games/supported/StarGunner.hpp \
    Util/cytonRL/ale/games/supported/Tennis.hpp \
    Util/cytonRL/ale/games/supported/Tetris.hpp \
    Util/cytonRL/ale/games/supported/TimePilot.hpp \
    Util/cytonRL/ale/games/supported/Trondead.hpp \
    Util/cytonRL/ale/games/supported/Turmoil.hpp \
    Util/cytonRL/ale/games/supported/Tutankham.hpp \
    Util/cytonRL/ale/games/supported/UpNDown.hpp \
    Util/cytonRL/ale/games/supported/Venture.hpp \
    Util/cytonRL/ale/games/supported/VideoPinball.hpp \
    Util/cytonRL/ale/games/supported/WizardOfWor.hpp \
    Util/cytonRL/ale/games/supported/YarsRevenge.hpp \
    Util/cytonRL/ale/games/supported/Zaxxon.hpp \
    Util/cytonRL/ale/games/Roms.hpp \
    Util/cytonRL/ale/games/RomSettings.hpp \
    Util/cytonRL/ale/games/RomUtils.hpp \
    Util/cytonRL/ale/os_dependent/OSystemUNIX.hxx \
    Util/cytonRL/ale/os_dependent/OSystemWin32.hxx \
    Util/cytonRL/ale/os_dependent/SettingsUNIX.hxx \
    Util/cytonRL/ale/os_dependent/SettingsWin32.hxx \
    Util/cytonRL/ale/ale_interface.hpp \
    Util/cytonRL/basicHeadsRl.h \
    Util/cytonRL/Environment.h \
    Util/cytonRL/NetworkRl.h \
    Util/cytonRL/ParamsRl.h \
    Util/cytonRL/ReinforceLearner.h \
    Util/cytonRL/ReplayMemory.h \
    Util/cytonRL/Step.h \
    Util/cytonRL/Steps.h \
    Util/cytonRL/SumTree.h \
    Util/cnn.h \
    World/#world.cpp#

FORMS    += \
    mainwindow.ui

RESOURCES += \
    res.qrc

CONFIG += c++11 \
    o3

DISTFILES += \
    tutorial.pro.user.ad5f1f3.4.8-pre1 \
    Util/cytonRL/ale/emucore/m6502/src/M6502.m4 \
    Util/cytonRL/ale/emucore/m6502/src/M6502Hi.m4 \
    Util/cytonRL/ale/emucore/m6502/src/M6502Low.m4 \
    tutorial.pro.user.26da0f2 \
    tutorial.pro.user.3b11ee3 \
    tutorial.pro.user.ad5f1f3 \
    Util/cytonRL/ale/common/stella.png \
    Util/cytonRL/ale/common/stella.xpm \
    Util/cytonRL/ale/common/module.mk \
    Util/cytonRL/ale/controllers/module.mk \
    Util/cytonRL/ale/emucore/m6502/src/bspf/Copyright.txt \
    Util/cytonRL/ale/emucore/m6502/src/bspf/License.txt \
    Util/cytonRL/ale/emucore/m6502/Copyright.txt \
    Util/cytonRL/ale/emucore/m6502/License.txt \
    Util/cytonRL/ale/emucore/m6502/module.mk \
    Util/cytonRL/ale/emucore/rsynth/Elements.def \
    Util/cytonRL/ale/emucore/rsynth/kmap \
    Util/cytonRL/ale/emucore/rsynth/module.mk \
    Util/cytonRL/ale/emucore/rsynth/phones.def \
    Util/cytonRL/ale/emucore/rsynth/phtoelm.def \
    Util/cytonRL/ale/emucore/rsynth/PORTING \
    Util/cytonRL/ale/emucore/module.mk \
    Util/cytonRL/ale/environment/module.mk \
    Util/cytonRL/ale/external/TinyMT/LICENSE.txt \
    Util/cytonRL/ale/external/module.mk \
    Util/cytonRL/ale/games/module.mk \
    Util/cytonRL/ale/os_dependent/module.mk \
    Util/cytonRL/ale/module.mk \
    Util/cytonLib/ActivationLayer.cu \
    Util/cytonLib/basicHeads.cu \
    Util/cytonLib/ConvolutionLayer.cu \
    Util/cytonLib/DeviceMatrix.cu \
    Util/cytonLib/DevMatReal.cu \
    Util/cytonLib/DueLinLayer.cu \
    Util/cytonLib/Global.cu \
    Util/cytonLib/HostMatReal.cu \
    Util/cytonLib/HostMatrix.cu \
    Util/cytonLib/Layer.cu \
    Util/cytonLib/LinearLayer.cu \
    Util/cytonLib/Matrix.cu \
    Util/cytonLib/MatrixGradient.cu \
    Util/cytonLib/Network.cu \
    Util/cytonLib/NumberProbe.cu \
    Util/cytonLib/NumberProbes.cu \
    Util/cytonLib/SoftmaxLayer.cu \
    Util/cytonLib/utils.cu \
    Util/cytonLib/Variable.cu \
    Util/cytonLib/Weight.cu \
    Util/cytonLib/WeightFactory.cu \
    Util/cytonRL/Environment.cu \
    Util/cytonRL/mainRl.cu \
    Util/cytonRL/NetworkRl.cu \
    Util/cytonRL/ParamsRl.cu \
    Util/cytonRL/ReinforceLearner.cu \
    Util/cytonRL/ReplayMemory.cu \
    Util/cytonRL/Step.cu \
    Util/cytonRL/Steps.cu \
    Util/cytonRL/SumTree.cu \
    Util/cytonRL/ale/emucore/rsynth/COPYING \
    Util/cytonRL/ale/emucore/m6502/src/M6502Hi.ins \
    Util/cytonRL/ale/emucore/m6502/src/M6502Low.ins

SUBDIRS += \
    Util/cytonRL/ale/emucore/stella.pro
